version: "3.4"
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        restart: always
        networks:
            - php-network
        volumes:
            - ./laravel-root:/var/www/app
            - ./laravel-root/public:/var/www/app/public
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

    lar-node:
        build: ./php/.
        volumes:
#            - ./common-cpa-pkg:/var/www/packages/
            - ./laravel-root:/var/www/app
            - ./laravel-root/public:/var/www/app/public
        networks:
            - php-network


    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - php-network
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password

networks:
    php-network:
        driver: bridge
